name: CD Pipeline
run-name: ${{ github.actor }} is currently deploying 🚀

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - name: Sending dist/
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.125.206.46 >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" dist/ ubuntu@13.125.206.46://home/ubuntu/nginx/html/
